// ============================================================
// LANGUAGE SYSTEM — Sauda (hi/en)
// ============================================================

const LANGUAGES = [
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'en', name: 'English', native: 'English' },
];

function getProductTitle(product) {
  var lang = state.userLang || 'hi';
  var map = {
    hi: product.titleHi || product.title,
    en: product.titleEn || product.title,
  };
  return map[lang] || product.title;
}

const TRANS = {
  site_title: { hi: 'Sauda — Bharose ka Sauda', en: 'Sauda — Trusted Marketplace' },
  sauda: { hi: 'Sauda', en: 'Sauda' },
  mohalla: { hi: 'Mohalla', en: 'Mohalla' },
  dukaan: { hi: 'Dukaan', en: 'Shop' },
  bol: { hi: 'Bol', en: 'Voice' },
  profile: { hi: 'Profile', en: 'Profile' },
  marketplace: { hi: 'Marketplace', en: 'Marketplace' },
  meri_dukaan: { hi: 'Meri Dukaan', en: 'My Shop' },
  categories_nav: { hi: 'Categories', en: 'Categories' },
  bol_ke_becho: { hi: 'Bol ke Becho', en: 'Voice Sell' },
  bol_ke_becho_title: { hi: 'Naya Listing Banao', en: 'Create New Listing' },
  tagline: { hi: 'Apne mohalle ke trusted sellers, apni aawaz se connect karo.', en: 'Connect with trusted local sellers using your voice.' },
  trust_tagline: { hi: 'Trust is a relationship, not a rating', en: 'Trust is a relationship, not a rating' },
  shuru_karein: { hi: 'Shuru Karein', en: 'Get Started' },
  skip: { hi: 'Skip for now', en: 'Skip for now' },
  choose_language: { hi: 'Apni bhasha chunein', en: 'Choose your language' },
  more_languages: { hi: 'Aur bhashayein', en: 'More languages' },
  back: { hi: 'Back', en: 'Back' },
  aap_kaun_hain: { hi: 'Aap kaun hain?', en: 'Who are you?' },
  choose_role: { hi: 'Choose your role to get started', en: 'Choose your role to get started' },
  buyer: { hi: 'Buyer', en: 'Buyer' },
  seller: { hi: 'Seller', en: 'Seller' },
  buyer_desc: { hi: 'Mohalle se best deals dhundho', en: 'Find the best deals in your neighborhood' },
  seller_desc: { hi: 'Apni dukaan online laao', en: 'Bring your shop online' },
  aage_badhein: { hi: 'Aage Badhein', en: 'Next' },
  apna_naam: { hi: 'Apna naam batayein', en: 'Tell us your name' },
  name_phone_instruction: { hi: 'We need this to build your trust profile', en: 'We need this to build your trust profile' },
  full_name: { hi: 'FULL NAME', en: 'FULL NAME' },
  phone_number: { hi: 'PHONE NUMBER', en: 'PHONE NUMBER' },
  apna_mohalla: { hi: 'Apna mohalla batayein', en: 'Tell us your locality' },
  auto_detect: { hi: 'Auto-detect Location', en: 'Auto-detect Location' },
  aadhaar_verify: { hi: 'Aadhaar Verification', en: 'Aadhaar Verification' },
  namaste: { hi: 'Namaste', en: 'Hello' },
  namaste_dukaandar: { hi: 'Namaste, Dukaandaar', en: 'Hello, Shopkeeper' },
  mohalla_market: { hi: 'Mohalla Market', en: 'Neighborhood Market' },
  categories_section: { hi: 'Categories', en: 'Categories' },
  sabhi_kshetra: { hi: 'Sabhi Kshetra', en: 'All Areas' },
  sabhi: { hi: 'Sabhi', en: 'All' },
  koi_listing_nahi: { hi: 'Koi listing nahi mila', en: 'No listings found' },
  search_placeholder: { hi: 'Apne mohalle mein dhundho...', en: 'Search in your neighborhood...' },
  live: { hi: 'LIVE', en: 'LIVE' },
  in_stock: { hi: ' in stock', en: ' in stock' },
  group_deal: { hi: 'Group Deal', en: 'Group Deal' },
  group_deal_sub: { hi: '3 log milke — 20% sasta', en: '3 people together — 20% off' },
  joined: { hi: 'Joined', en: 'Joined' },
  you: { hi: 'Aap', en: 'You' },
  friend: { hi: 'Friend', en: 'Friend' },
  deal_active: { hi: 'Deal Active!', en: 'Deal Active!' },
  group_deal_join: { hi: 'Group Deal Mein Shamil Ho', en: 'Join Group Deal' },
  meri_listings: { hi: 'Meri Listings', en: 'My Listings' },
  listings_stat: { hi: 'Listings', en: 'Listings' },
  aaj_orders: { hi: 'Aaj Orders', en: '' },
  revenue: { hi: 'Revenue', en: 'Revenue' },
  manual: { hi: 'Manual', en: 'Manual' },
  voice: { hi: 'Voice', en: 'Voice' },
  add_item: { hi: 'Add Item', en: 'Add Item' },
  apna_item_bolo: { hi: 'Apna item bolo', en: 'Say your item' },
  bolein: { hi: 'Bolein', en: 'Speak' },
  kripya_fill: { hi: 'Kripya title, category aur price fill karein', en: 'Please fill title, category and price' },
  browse_categories: { hi: 'Browse Categories', en: 'Browse Categories' },
  sab_kuch: { hi: 'Sab kuch apne mohalle se', en: 'Everything from your neighborhood' },
  items_label: { hi: ' items', en: ' items' },
  sellers_count: { hi: ' sellers, ', en: ' sellers, ' },
  products_count: { hi: ' products', en: ' products' },
  mic_hint: { hi: 'Mic tap karein — Hindi mein bolein', en: 'Tap mic — speak in Hindi' },
  sun_raha_hoon: { hi: 'Sun raha hoon...', en: 'Listening...' },
  samajh_raha: { hi: 'Samajh raha hoon...', en: 'Processing...' },
  listing_taiyaar: { hi: 'Listing taiyaar kar raha hoon...', en: 'Preparing listing...' },
  listing_publish: { hi: 'Listing Publish Karein', en: 'Publish Listing' },
  publish_hint: { hi: 'Bol ke ya likhakar', en: 'By voice or writing' },
  aapki_aawaz: { hi: 'Aapki Aawaz', en: 'Your Voice' },
  demo_hindi: { hi: 'Demo: Hindi Voice Simulation', en: 'Demo: Hindi Voice Simulation' },
  sauda_karein: { hi: 'Sauda Karein', en: 'Place Order' },
  trust_score: { hi: 'Trust Score', en: 'Trust Score' },
  aadhaar_tag: { hi: 'Aadhaar', en: 'Aadhaar' },
  aadhaar: { hi: 'Aadhaar', en: 'Aadhaar' },
  vouchchain: { hi: 'VouchChain', en: 'VouchChain' },
  vouchchain_sub: { hi: 'Bharose ka rishta, rating nahi', en: 'Trust is a relationship, not a rating' },
  bol_ke_kharido: { hi: 'Bol ke Kharido', en: 'Voice Buy' },
  voice_buy_subtitle: { hi: 'Jo chahiye, boliye — hum dhundh denge', en: 'Speak what you need — we will find it' },
  searching_products: { hi: 'Dhundh raha hoon...', en: 'Searching products...' },
  search_results: { hi: 'Search Results', en: 'Search Results' },
  quantity: { hi: 'Quantity', en: 'Quantity' },
  total: { hi: 'Total', en: 'Total' },
  dekho_kaun: { hi: 'Dekho kaun kisko trust karta hai', en: 'See who trusts whom' },
  notifications: { hi: 'Notifications', en: 'Notifications' },
  koi_notification_nahi: { hi: 'Koi notification nahi', en: 'No notifications' },
  my_orders: { hi: 'My Orders', en: 'My Orders' },
  koi_order_nahi: { hi: 'Abhi tak koi order nahi', en: 'No orders yet' },
  pehla_sauda: { hi: 'Pehla Sauda karein!', en: 'Make your first order!' },
  saved_sellers: { hi: 'Saved Sellers', en: 'Saved Sellers' },
  ne_vouch_kiya: { hi: 'ne vouch kiya', en: 'vouched' },
  available: { hi: ' available', en: ' available' },
  saal: { hi: ' saal', en: ' yrs' },
  neighbors: { hi: ' neighbors', en: ' neighbors' },
  active: { hi: 'Active', en: 'Active' },
  trusted_connections: { hi: 'trusted connections', en: 'trusted connections' },
  or_enter: { hi: 'YA PHIR LIKHEIN', en: 'OR ENTER MANUALLY' },
  shop_name_label: { hi: 'DUKAAN KA NAAM', en: 'SHOP NAME' },
  category_select_label: { hi: 'SHREENI (SARI LAGU HONE PAR CHUNEIN)', en: 'CATEGORY (Select all that apply)' },
  vouches_count: { hi: 'Vouches', en: 'Vouches' },
  vouchchain_trust_path: { hi: 'VOUCHCHAIN — TRUST PATH', en: 'VOUCHCHAIN — TRUST PATH' },
  voice_item_detected: { hi: 'Voice se item detect kiya!', en: 'Item detected by voice!' },
  item_added_voice: { hi: 'Item add ho gayi! Voice se add kiya.', en: 'Item added! Added by voice.' },
  item_added_manual: { hi: 'Item add ho gayi! Dukaan mein dikhegi.', en: 'Item added! It will appear in your shop.' },
  kripya_sab_details: { hi: 'Kripya sab details fill karein', en: 'Please fill all details' },
  item_published: { hi: 'Listing publish ho gayi! Dukaan mein dikhegi.', en: 'Listing published! It will appear in your shop.' },
  tap_to_join_deal: { hi: 'Tap to join this deal', en: 'Tap to join this deal' },
  three_log_mil_gaye: { hi: '3 log mil gaye — 20% discount laga hai', en: '3 people joined — 20% discount applied' },
  notif_order_deal: { hi: 'Priya ne Banarasi Silk Saree ka deal kiya', en: 'Priya made a deal for Banarasi Silk Saree' },
  notif_new_seller: { hi: 'Naya seller: Rajesh Mobile Corner aaya', en: 'New seller: Rajesh Mobile Corner arrived' },
  notif_group_deal: { hi: 'Group Deal: 3 log milke 20% sasta!', en: 'Group Deal: 3 people get 20% off!' },
  group_deal_joined_notif: { hi: 'Group Deal active! Banarasi Silk Saree — 20% off', en: 'Group Deal active! Banarasi Silk Saree — 20% off' },
  group_deal_joined_toast: { hi: 'Group Deal mein shamil ho gaye! 20% sasta!', en: 'You joined the group deal! 20% off!' },
  profile_orders: { hi: 'Orders', en: 'Orders' },
  profile_listings: { hi: 'Listings', en: 'Listings' },
  profile_saved: { hi: 'Saved', en: 'Saved' },
  profile_vouches: { hi: 'Vouches', en: 'Vouches' },
  profile_updated: { hi: 'Profile update ho gaya!', en: 'Profile updated!' },
  role_changed_to: { hi: 'Role badal gaya:', en: 'Role changed to:' },
  phone_number_display: { hi: 'Phone number', en: 'Phone number' },
  phone: { hi: 'Phone', en: 'Phone' },
  location: { hi: 'Location', en: 'Location' },
  listings_header: { hi: 'LISTINGS', en: 'LISTINGS' },
  koi_seller_nahi: { hi: 'Koi saved seller nahi', en: 'No saved sellers' },
  heart_icon_hint: { hi: 'Product detail mein heart icon tap karein', en: 'Tap the heart icon on product detail' },
  tap_hint: { hi: 'TAP', en: 'TAP' },
  abhi: { hi: 'Abhi', en: 'Just now' },
  min_pehle: { hi: ' min pehle', en: ' min ago' },
  ghante_pehle: { hi: ' ghante pehle', en: ' hours ago' },
  din_pehle: { hi: ' din pehle', en: ' days ago' },
  sauda_pakka: { hi: 'Sauda Pakka!', en: 'Order Confirmed!' },
  order_sent_success: { hi: 'Aapki request bhej di gayi hai. Trust network ke through deal secure hai.', en: 'Your request has been sent. The deal is secured through the trust network.' },
  vouchchain_secured: { hi: 'VOUCHCHAIN SECURED', en: 'VOUCHCHAIN SECURED' },
  marketplace_wapas: { hi: 'Marketplace Mein Wapas Jayein', en: 'Back to Marketplace' },
  saved_tost: { hi: ' saved!', en: ' saved!' },
  removed_saved_tost: { hi: ' removed from saved', en: ' removed from saved' },
  confirmed: { hi: 'CONFIRMED', en: 'CONFIRMED' },
  lang_select: { hi: 'भाषा चुनें', en: 'Select Language' },
  edit_profile: { hi: 'Profile Edit karein', en: 'Edit Profile' },
  role_label: { hi: 'Role', en: 'Role' },
  aadhaar_verified: { hi: 'Aadhaar Verified', en: 'Aadhaar Verified' },
  save_changes: { hi: 'Save Changes', en: 'Save Changes' },
  verified: { hi: 'Verified', en: 'Verified' },
  tap_to_update: { hi: 'Tap to update', en: 'Tap to update' },
  interests_label: { hi: 'Interests', en: 'Interests' },
  select_categories: { hi: 'Select categories', en: 'Select categories' },
  reset_demo: { hi: 'Reset Demo', en: 'Reset Demo' },
  reset_demo_desc: { hi: 'Clear all data & restart', en: 'Clear all data & restart' },
  sauda_version: { hi: 'Sauda v0.2 — Bharose ka Sauda', en: 'Sauda v0.2 — Trust-based Commerce' },
  your_name_placeholder: { hi: 'Aapka naam', en: 'Your name' },
  location_placeholder: { hi: 'Jaise Lalghati, Bhopal', en: 'e.g. Lalghati, Bhopal' },
  yes_label: { hi: 'Haan', en: 'Yes' },
  no_label: { hi: 'Nahi', en: 'No' },
  not_registered_tag: { hi: 'Sauda par nahi', en: 'Not on Sauda yet' },
  not_listed_yet: { hi: 'Abhi listed nahi', en: 'Not listed yet' },
  open_now: { hi: 'Khula hai', en: 'Open now' },
  closed_now: { hi: 'Band hai', en: 'Closed now' },
  more_shops_in_area: { hi: 'Is kshetra mein aur dukanein', en: 'More shops in this area' },
  name_required: { hi: 'Naam zaroori hai', en: 'Name is required' },
  shop_details: { hi: 'Apni dukaan ki details', en: 'Your shop details' },
  tell_shop: { hi: 'Tell us about your shop', en: 'Tell us about your shop' },
  kya_kharidte: { hi: 'Kya kya kharidte hain?', en: 'What do you buy?' },
  select_interests: { hi: 'Select your interests for personalized feed', en: 'Select your interests for personalized feed' },
  apne_mohalle_trusted: { hi: 'So we can show nearby trusted sellers', en: 'So we can show nearby trusted sellers' },
};

function getText(key) {
  var lang = state.userLang || 'hi';
  var t = TRANS[key];
  if (!t) return key;
  return t[lang] || t['hi'] || t['en'] || key;
}

function __(key) {
  return getText(key);
}

function getCategoryName(cat) {
  if (!cat) return '';
  var lang = state.userLang || 'hi';
  if (lang === 'hi') return cat.name || cat.nameEn || cat.id;
  return cat.nameEn || cat.name || cat.id;
}
